name: Rebuild events section from github docs


on:
  workflow_dispatch:
    inputs:
      SOURCE:
        required: true
        default: "https://raw.githubusercontent.com/github/docs/main/content/actions/using-workflows/events-that-trigger-workflows.md"
  schedule:
    - cron: '0 0 * * *'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python rebuild_events.py
        env:
          SOURCE: ${{ inputs.SOURCE || 'https://raw.githubusercontent.com/github/docs/main/content/actions/using-workflows/events-that-trigger-workflows.md'}}
      - uses: EndBug/add-and-commit@v9
        id: commit
        with:
          add: zsh/_act
          message: "Updated completion per changes in github/docs"
      - run: gh workflow run "CI - tag and release"
        if: steps.commit.outputs.committed
        env:
          GH_TOKEN: ${{ github.token }}
